### ISSUE TITLE
CPU 100%

### ISSUE THREAD

**Issue by H1D** [remcoder/chronos#1]
Have a strange problem. Changed this:

``` coffeescript
Template.guestRow.helpers
  time_spent: -> moment( @start_time ).fromNow()
```

to this

``` coffeescript
Template.guestRow.helpers
  time_spent: -> Chronos.liveMoment( @start_time ).fromNow()
```

got CPU load 100% and totally unresonsive app

Meteor version - 1.0.3.1

**Comment by remcoder** [comment]
Hmm that's weird. I have the feeling something else is hogging the CPU. The default interval between reactive updates is 1000ms (1 second). 

If the problem persists, could you post a little more code, like the template and all its helpers?

**Comment by maxnowack** [comment]
@H1D did you fixed it?
same problem here...

**Comment by maxnowack** [comment]
here is an example: https://github.com/maxnowack/chronos-example

**Comment by remcoder** [comment]
Thanks for the testcase! Yes I see the problem now. I'll fix it ASAP.

**Comment by remcoder** [comment]
Just pushed a fix to Atmosphere. See if that works for you.

**Comment by maxnowack** [comment]
great, it works!
Thanks :+1:
