### ISSUE TITLE
Error installing in Meteor 1.3.3 on Windows

### ISSUE THREAD

**Issue by airedale302** [remcoder/chronos#11]
As soon as I did a "meteor update" to upgrade to 1.3.3, I got an error C:\Users\Airedale\AppData\Local.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
Error: ENOENT, open 'C:\Users\Airedale\AppData\Local\Temp\mt-1n5omma\os\remcoder:chronos.js'

I then removed the remcoder:chronos package and reinstall "meteor update remcoder:chronos" and got the same error again.

Now I cannot install at all. Looks like promise_server.js from meteor-tool 1.3.3 has problem with remcoder:chronos.

**Comment by remcoder** [comment]
Weird. I don't see any Chronos specifics in the stack trace other than that
the main file could not be loaded. Could you verify this problem is
specific to Chronos?

**Comment by airedale302** [comment]
Hi,

I don't actually know. I just know that after I "meteor update" to Meteor
1.3.3, I cannot install remcoder:chronos.

I am able to install a similar package on Meteor 1.3.3 with "meteor update
panter:moment-reactive".

Strangely, I try to add remcoder:chronos to a different app that is still
under Meteor 1.3.2, and I got the same error:

C:\Meteor\tcm2>meteor add remcoder:chronos

C:\Users\Airedale\AppData\Local.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
      throw error;
            ^
Error: ENOENT, open
'C:\Users\Airedale\AppData\Local\Temp\mt-18qb0td\os\remcoder:chronos.js'

I don't know if the problem is specific with Chronos or with my particular
setup.

**Comment by remcoder** [comment]
Which Chronos version did you try to install in the 1.3.2 project?

**Comment by remcoder** [comment]
Did the error actually occur when running meteor install remcoder:chronos
or when running your application after the installation?

**Comment by airedale302** [comment]
The error occurred when I tried to install with "meteor add
remcoder:chronos". The package never get installed.

Before I updated Meteor to 1.3.3, I was able to install remcoder:chronos.

The version of Chronos I tried to install was 0.4.2, which is what gets
delivered by atmospherejs.com when I run "meteor add remcoder:chronos". The
version number momentarily flashed on the screen just before the error
message popped up.

**Comment by remcoder** [comment]
Sorry about the delay. I can reproduce the issue on Windows 10 but not on my Mac, so I think it it Windows specific. Meteor tries to load the file remcoder:chronos.js from a temporary directory but the directory does not exist at all.

**Comment by remcoder** [comment]
Currently I have no idea how to approach this issue, unfortunately. Help would be appreciated, any suggestion or brain fart will do...

**Comment by slevr** [comment]
I updated to latest meteor and get same error - using Windows 7. I'm not real familiar with meteor packages but I'm thinking it relates to the naming of your remcoder:chronos.js file. And how it's added via api.addFiles('remcoder:chronos.js');

Perhaps rename to remcoder-chronos.js ?

**Comment by remcoder** [comment]
thx @slevr! Indeed the colon was the culprit. I've fixed it in the v0.5.x branch which I will deploy asap.

**Comment by remcoder** [comment]
v0.5.0 was just published, which fixes this issue. Sorry it took so long (apparently this issue was present from the very first version of Chronos) and thx to @slevr for suggesting a solution :D
