### ISSUE TITLE
Unclear docs

### ISSUE THREAD

**Issue by H1D** [remcoder/chronos#2]
Docs says:

> If the global variable moment exists in your app, this function will wrap it to make it update reactively based on a **timer**.

it is unclear.. based on what timer? Have a bunch of template helpers using `momentjs` what should I do to make them autoupdateble

**Comment by remcoder** [comment]
Basically it says that `Chronos.liveMoment()` is a reactive replacement for the global function `moment()`. You'll need to include momentjs yourself and the reason being that there are several different versions of momentjs on Atmosphere. 

The underlying timer is a `Chronos.Timer`, which you'll find in the docs. So the underlying timer will trigger `Chronos.liveMoment()` every interval (which defaults to 1000ms).

To use it inside a template helper you can do something like this:

```
var start = new Date();

Template.foo.helpers({
    timeSpent : function() {
        return Chronos.liveMoment(start).fromNow();
    }
})
```

**Comment by remcoder** [comment]
I updated the docs with clearer wording and more examples. This should do it for now I guess.

**Comment by H1D** [comment]
:+1:
