### ISSUE TITLE
Memory leak / no way to destroy liveUpdate

### ISSUE THREAD

**Issue by mattkrick** [remcoder/chronos#6]
Currently, a `liveUpdate` is never destroyed.
This can be seen by slipping in the following right before the `return`

```
console.log(_timers);
```

When navigating away from the current page, then going back, you'll see the `_timers` object grows, keeping all the previous computation Ids.

**Comment by remcoder** [comment]
Is this in combination with IronRouter? Or some other client-side router?

**Comment by mattkrick** [comment]
Yep, using Iron Router

**Comment by remcoder** [comment]
When navigating away Iron Router stops the reactive context the timer is running in (by destroying the template instance). Chronos now handles this case and stops the timer and removes it from the list. Also, I've added a destroy method you can call to do the same.

Please let me know if this works for you.
