### ISSUE TITLE
when to use Chronos.Timer.stop()

### ISSUE THREAD

**Issue by avalanche1** [remcoder/chronos#9]
Hey, Remco! Thanks for the really kewl package!
Q: Do I have to call Chronos.Timer.stop() when I use Chronos.liveUpdate & Chronos.liveMoment?

**Comment by remcoder** [comment]
Hi there! It depends ;-) If you just want to let the timer run then you
don't need to call stop(). What's your scenario?

**Comment by remcoder** [comment]
Also, Chronos takes care of cleaning up the timer when you navigate away from the page (like when you use Iron:router)

**Comment by avalanche1** [comment]
`Chronos takes care of cleaning up the timer when you navigate away from the page` - yep, that's what I needed. Nice)
